[default]
extend-ignore-identifiers-re = [
    "AttributeID.*Supress.*",
]

[default.extend-identifiers]
AttributeIDSupressMenu = "AttributeIDSupressMenu"

[default.extend-words]
iy = "iy"
ths = "ths"
asend = "asend"
alph = "alph"
fo = "fo"
thi = "thi"
doub = "doub"
Doub = "Doub"
Numer = "Numer"
thr = "thr"
nd = "nd"