name: 'Test on MacOS'

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
  self:
    name: Mac Runner
    runs-on: macos-latest
    # continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build Packages
        run: |
            set -x
            brew install gcc mpich gfortran-10
            export PATH=$PATH:/usr/local/bin
            gfortran -v
            ./rbc.sh install-mac

      - name: Compile Cases
        run: |
            set -e -x
            export PETSC_DIR=`pwd`/packages/petsc-3.21.3
            export PETSC_ARCH=arch-linux-c-opt
            mkdir build
            cd build
            cmake ..
            make
            echo "/common and all cases in /examples compiled successfully!"

