# name: 'Test on MacOS'

# on:
#     push:
#     pull_request:
#     workflow_dispatch:

# jobs:
#   self:
#     name: Mac Runner
#     runs-on: macos-latest
#     if: github.repository == 'Comp-Physics/RBC3D'
#     continue-on-error: true
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
      
#       - name: Build Packages
#         run: |
#             set -x
#             brew install gcc mpich gfortran pkg-configa
#             ln -s /opt/homebrew/bin/gfortran-14 /usr/local/bin/gfortran
#             ./rbc.sh install-mac

#       - name: Compile Cases
#         run: |
#             set -e -x
#             export PETSC_DIR=`pwd`/packages/petsc-3.21.3
#             export PETSC_ARCH=arch-darwin-c-opt
#             mkdir build
#             cd build
#             cmake ..
#             make
#             echo "/common and all cases in /examples compiled successfully!"

