name: Pretty

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  docs:
    name:    Code formatting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check formatting
      run: |
        bash rbc.sh format
        git diff --exit-code
