name: Spell Check
on:
  push:
  workflow_dispatch:

jobs:
  run:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Spell Check
      uses: check-spelling/check-spelling@v0.0.21