name: 'Test on Phoenix'

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
  self:
    name: Phoenix Runner
    runs-on:
      - self-hosted
    if: github.repository == 'Comp-Physics/RBC3D'
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Build
        run: |
          ml anaconda3/2021.05 gcc mvapich2 mkl python/3.9.12-rkxvr6 netcdf-c netcdf-cxx netcdf-fortran fftw
          bash rbc.sh install-no-petsc

      - name: Test
        run: |
          ml gcc mvapich2 mkl netcdf-c netcdf-cxx netcdf-fortran fftw
          cd common
          make .depend
          make
          cd ../examples/case
          make .depend
          make