name: 'Test on Phoenix'

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
  self:
    name: Georgia Tech | Phoenix
    runs-on:
      - self-hosted
    steps:
      - name: Test
        run: |
          sbatch ./.github/workflows/phoenix/submit.sh
          wait %1