name: 'Test on Phoenix'

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
  self:
    name: Phoenix Runner
    runs-on:
      - self-hosted
    if: github.repository == 'Comp-Physics/RBC3D'
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Load Modules
        run: |
          ml gcc mvapich2 mkl petsc netcdf-c netcdf-cxx netcdf-fortran fftw

      - name: Build
        run: |
          bash rbc.sh install-no-petsc

      - name: Test
        run: |
          cd common
          make .depend
          make
          cd ../examples/case
          make .depend
          make