name: 'Test on Phoenix'

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
  self:
    name: Phoenix Runner
    runs-on:
      - self-hosted
    if: github.repository == 'Comp-Physics/RBC3D'
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build & Test
        run: |
          sbatch .github/scripts/submit.sh
          wait %1
          cat examples/case/ci.log