name: 'Test on Phoenix'

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
  self:
    name: Georgia Tech | Phoenix
    runs-on:
      group:  phoenix
      labels: gt
    steps:
      - name: Test
        run: |
          sbatch .github/workflows/phoenix/submit.sh
          wait %1